### ISSUE TITLE
modulefile names

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/tools#2] opened 2015-08-30 10:34 UTC
Would it be possible to have all module files LOWERCASE ?

**Comment by gppezzi** [comment] 2015-08-31 08:05
Yes but we would lose the readability and it would be painful to keep our easyconfig files in sync after every easybuild release.

If the case sensitive "module available" is the problem, you can for example use grep -i or switch to lmod:

perettig@dora101:~> ml av -t python
/apps/dora/modulefiles:
python/
python/2.7.7
/apps/dora/easybuild/modules/all:
IPython/
IPython/3.2.0-CrayGNU-5.2.40-Python-2.7.9
PyZMQ/14.7.0-CrayGNU-5.2.40-Python-2.7.9-zmq3
(...)

**Comment by boegel** [comment] 2015-09-02 18:53
Actually, you don't have to modify your easyconfig files at all.

All you need to do is implement a simple custom module naming scheme, and configure EasyBuild to be aware of it (via `--include-module-naming-schemes` configuration option) and to use it (via the `--module-naming-scheme` configuration option). You'll need EasyBuild v2.3.0 (released just today) for this, since `--include-module-naming-schemes` was actually unusable in v2.2.0 (where it was introduced).

If you're happy with the EasyBuild default module names otherwise, the implementation of the module naming scheme would be fairly trivial, something like (untested, but likely works):

```python
from easybuild.tools.module_naming_scheme.easybuild_mns import EasyBuildMNS

class LowerCaseEasyBuildMNS(EasyBuildMNS):

    def det_full_module_name(self, ec):
        modname = super(LowerCaseEasyBuildMNS, self).det_full_module_name(ec)
        return modname.lower()
```

**Comment by gppezzi** [comment] 2015-09-03 07:15
Thanks for the info Kenneth.

After talking to JG I realised that the origin of the problem is the search with "module av module_name" that was bothering him, since our module tools is case sensitive.

I don't really like the idea of changing all module names as a solution to JG's "module av" problem, as it would be way simpler to fix that on the modules search (adding a new alias or using lmod or grep -i).

I will close this issue for now and we can re-open it if we have feedback from other people or if we decide that EB's default naming scheme is not OK for us.

**Closed by gppezzi** 2015-09-03 07:15 UTC

**Comment by boegel** [comment] 2015-09-03 07:19
Going with Lmod is definitely a good option, yes, there's many other things that are much nicer with Lmod besides case-insensitive `module avail` (by default).

Don't hesitate to let me know if you need help, either with using a custom module naming scheme or Lmod.
